server:
  port: @server.port@
management:
  security:
    flag: false
  metrics:
    export:
      statsd:
        flavor: etsy
        enabled: false
spring:
  application:
    name: @project.name@
  output:
    ansi:
      enabled: always

  banner:
    image:
      location: "shampune.png"
      invert: true


  info:
  version: @project.version@
  stage: dev

