server:
  port: @server.port@
management:
  security:
    flag: false
  metrics:
    export:
      statsd:
        flavor: etsy
        enabled: false
spring.datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: @db.url@
    username: @db.user@
    password: @db.password@
    hikari.maximum-pool-size: 10
    hikari.idle-timeout: 30000
spring:
  application:
    name: shumpune
  output:
    ansi:
      enabled: always

  banner:
    image:
      location: "shampune.png"
      invert: false


  info:
  version: @project.version@
  stage: dev

